### ISSUE TITLE
Order of related events

### ISSUE THREAD

**Issue by thaoms** [solspace/craft3-calendar#19]
What is the order of the events of the relationship field?

It seems you can drag and drop but after save it is reverted to, what seems to be, ordered on start date.

And this doesn't reflect in the template
`production.relatedEvents.ids`

This returns a different order than what the fieldtype visually shows.

So is the drag and drop broken? And why are the ids in a different order (would be nice if it was in the same order, so we don't have to fetch them with the calendar.events tag just for reordering).

**Comment by kjmartens** [comment]
Just to clarify, you're saying that it appears that you can't reorder the related events with the Calendar fieldtype? I can duplicate this as well, and we'll work on a fix for it. Thanks :)

**Comment by thaoms** [comment]
Yes, and when outputting `.relatedEvents.ids` it shows the ids in the same order as in the CMS

**Comment by kjmartens** [comment]
This should now be fixed in Beta 10 as well :)

**Comment by johndwells** [comment]
I don't know if it's wise to comment on this very old issue, but this is happening (again?) with Craft 5.6.14 and Calendar Pro 5.0.16.

Here's a loom of our experience:

https://www.loom.com/share/2935fa62f87046d583c4b38ac21c7968?sid=51745618-71fc-4dd4-b505-089d206bf512

Steps:

1. Configure Calendar Events field type
2. Add field to entry layout (Single in our case)
3. Edit entry and add events, reordering them
4. Save changes

Expected Behavior: custom order should be maintained

Actual Behavior: order is reset (I can't really tell which order it's defaulting to).

**Comment by johndwells** [comment]
@kjmartens Any thoughts on this? Our only recourse is to reach for a matrix field, which as you can appreciate is less than ideal from a perf & UI POV.

**Comment by kjmartens** [comment]
Sorry about this @johndwells,

I can duplicate this in my testing as well. I'll see if we're able to get around this issue. 🙂
