### ISSUE TITLE
Is this plugin suposed to work with craft 3.5 and php 7.4?

### ISSUE THREAD

**Issue by lucashfreitas** [solspace/craft3-calendar#34]
I've updated craft and php version therefore pages with the calendar are not working. It throwing an exception when trying to use `Nesbot` getter date. 

Carbon\Exceptions\UnknownGetterException: Unknown getter 'date' in /var/www/vendor/nesbot/carbon/src/Carbon/Traits/Date.php:1017

I will do further investigation to debug the issue and will post if I find anything here.

**Comment by kjmartens** [comment]
Hi @lucashfreitas,

Sorry for the long delay. Not sure why this one slipped through the cracks, but I'm curious if this issue is still affecting you? There shouldn't be any compatibility issues with PHP 7.4 and Craft 3.5 that we're aware of. :)

**Comment by brandondeweese** [comment]
This is happening to me as well. Any fix found?

**Comment by kjmartens** [comment]
@brandondeweese Which version of Craft and Calendar are you currently using? And I assume you have PHP 7.4?

**Comment by brandondeweese** [comment]
Yes... switching to 7.3 to see if that works. It was working fine on my staging which had 7.3. 
Latests versions of both. Calendar  3.3.8 and Craft Pro 3.7.30.1

**Comment by kjmartens** [comment]
How are you upgrading the production site? If you're just pushing the files from Staging to Production, you need to make sure they are both the same, or at least have the same PHP version, otherwise your staging environment is grabbing PHP 7.3 compatible versions of the vendor dependencies, and placing those in a PHP 7.4 environment.

To resolve this, you should either update your Staging environment to PHP 7.4 as well, so when you run `composer update`, it'll at least grab compatible vendor dependencies and likely not run into issues when pushing to production. 🙂

**Comment by brandondeweese** [comment]
Well I've downgraded to 7.3. Nothing changed. Upgraded back to 7.4 and changed the dependencies in my composer, removed vendor folder and composer.lock, cleared cache, killed all the process, and reinstalled. Nothing changed Still getting this error. I'll push to another directory and see if that fixes it, i guess.
